name: ancestors-golang

on: [push]

jobs:
  static-check:
    runs-on: ubuntu-20.04      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
     # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run static-checks
      run: task static-check 
  test:
    name: Test
    runs-on: ubuntu-20.04 
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test -cover ./...
      
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV}}
          file: ./coverage.txt